[template]
src = "consul.crt.tmpl"
dest = "/consul/config/consul.crt"
owner = "root"
mode = "0644"
keys = [
  "/services/consul/metadata/consul1.crt",
  "/services/consul/metadata/consul2.crt",
  "/services/consul/metadata/consul3.crt",
  "/self/container/service_index",
]
