version: '2'
services:
  consul:
    image: drpebcak/consul:1.0.0
    network_mode: host
    volumes:
    - /consul/config
    - /consul/data
    labels:
      io.rancher.sidekicks: consul-conf
      io.rancher.container.dns: true
  consul-conf:
    image: drpebcak/consul-config:1.0.0
    network_mode: service:consul
    volumes_from:
    - consul
    labels:
      io.rancher.container.hostname_override: container_name
