version: '2'
services:
  consul:
    image: husseingalal/consul
    network_mode: host
    volumes:
    - /consul/config
    - /consul/data
    labels:
      io.rancher.sidekicks: consul-conf
      io.rancher.container.dns: true
  consul-conf:
    image: registry.example.com:5000/consul-config:master
    network_mode: service:consul
    volumes_from:
    - consul
    labels:
      io.rancher.container.hostname_override: container_name
